// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUtcgeDA9gm-UDbpRe4eROeOLbwy11QDQ',
    appId: '1:795762511515:web:63c3509cc1a44fd272c03e',
    messagingSenderId: '795762511515',
    projectId: 'netsearch-585eb',
    authDomain: 'netsearch-585eb.firebaseapp.com',
    storageBucket: 'netsearch-585eb.firebasestorage.app',
    measurementId: 'G-4HKFGTRN2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3b2v1c1Fj1h8s_s2RgYZPb_ZA5dUxCc',
    appId: '1:795762511515:android:2fe413214b3bc67872c03e',
    messagingSenderId: '795762511515',
    projectId: 'netsearch-585eb',
    storageBucket: 'netsearch-585eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXZfWUEkNv4n-WLIEdazh_pnLgmD74fLo',
    appId: '1:795762511515:ios:31e72ff67b02760872c03e',
    messagingSenderId: '795762511515',
    projectId: 'netsearch-585eb',
    storageBucket: 'netsearch-585eb.firebasestorage.app',
    iosBundleId: 'com.example.netSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXZfWUEkNv4n-WLIEdazh_pnLgmD74fLo',
    appId: '1:795762511515:ios:31e72ff67b02760872c03e',
    messagingSenderId: '795762511515',
    projectId: 'netsearch-585eb',
    storageBucket: 'netsearch-585eb.firebasestorage.app',
    iosBundleId: 'com.example.netSearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUtcgeDA9gm-UDbpRe4eROeOLbwy11QDQ',
    appId: '1:795762511515:web:0b7f9fc4f828a0df72c03e',
    messagingSenderId: '795762511515',
    projectId: 'netsearch-585eb',
    authDomain: 'netsearch-585eb.firebaseapp.com',
    storageBucket: 'netsearch-585eb.firebasestorage.app',
    measurementId: 'G-73Z17PBB19',
  );
}
